module.exports.authService = require('./auth.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.cateService = require('./category.service')
module.exports.recipeService = require('./recipe.service')
module.exports.newsService = require('./news.service')
module.exports.companyService = require('./company.service')
