module.exports.authController = require('./auth.controller')
module.exports.userController = require('./user.controller')
module.exports.cateController = require('./category.controller')
module.exports.newsController = require('./news.controller')
module.exports.companyController = require('./company.controller')
module.exports.recipeController = require('./recipe.controller')
